### ISSUE TITLE
HTML::Tidy fails to install when tidyp not already installed

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckgo-publisher#123]
I ran into this issue today trying to install Publisher on my Mac. It seems you need the C program `tidyp` installed for `HTML::Tidy` to successfully install.

`HTML::Tidy` docs explain that installing `Alien::Tidyp` will install `tidyp` for you. Should we add `Alien::Tidyp` to the dist.ini then?

**Comment by sudheesh001** [comment]
Could reproduce this, I think it's good to put up Alien::Tidyp into the dist.ini file
