### ISSUE TITLE
Search Box iframe ARIA Role

### ISSUE THREAD

**Issue by plfstr** [duckduckgo/duckduckgo-publisher#178]
The iframe generated to embed a [search box](https://duckduckgo.com/search_box) could include `role="search"` [ARIA landmark](http://www.w3.org/TR/wai-aria/roles#search) to aid with accessibility.

**Comment by moollaza** [comment]
@plfstr thanks for the suggestion! Would you be interested in making a PR?

**Comment by plfstr** [comment]
@moollaza I think you can close this issue or approach it from the markup within the iframe. Tested in VoiceOver and ChromeVox and neither announced the search role either as a landmark, or when you tab into the search box. So it seems it does not aid accessibility applying it to the iframe. Sorry.

**Comment by moollaza** [comment]
@plfstr thanks for the update. Closing this then.
