### ISSUE TITLE
Use target=_blank for in-line links in documentation so they open in a new tab

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckgo-publisher#197]
We have a lot of in-line links to external pages in the documentation. It might be good to force these to open in a new tab so we don't take users off of duck.co unexpectedly.

**Comment by preemeijer** [comment]
Hello @moollaza 
is this still relevant? If so could I take this one... with some low priority?
Cheers

**Comment by moollaza** [comment]
@preemeijer I think we're trying to minimize changes to this repo right now as we're going to be deprecating it shortly, for now I think this issue can be closed 👍
