### ISSUE TITLE
/bang : broken link to image

### ISSUE THREAD

**Issue by fzzr-** [duckduckgo/duckduckgo-publisher#238]
Broken link [here: site/duckduckgo/bang.tx](https://github.com/duckduckgo/duckduckgo-publisher/blob/daa94195e3a14a189d655f403049ee4f8e02b4cf/share/site/duckduckgo/bang.tx#L23-L25)

![ddg bang img issue mov opt](https://cloud.githubusercontent.com/assets/888526/13779589/c6cedf5a-eacc-11e5-8024-42fd0df7a511.gif)

In html i see:

```html
<img class="js-lazyretina no-js__hide bang--about__screenshot" src="/assets/bang/screenshot" data-src="/assets/bang/screenshot">
```

I don't know why `/assets/bang/screenshot` without `.png`. I have no any plugin what can modify src attr of img.

**Comment by andrey-p** [comment]
Hey @fzzr-, thanks for reporting this issue! We're aware of it, and a fix is going out later today. I'll close when it happens.

**Comment by andrey-p** [comment]
Annnnnnnd, it's fixed!

![screenshot_2016-03-15_17-27-08](https://cloud.githubusercontent.com/assets/1431577/13787284/41376aa4-ead3-11e5-8007-32d0c9aef7a0.png)
